### ISSUE TITLE
sandcats.io certificate expired

### ISSUE THREAD

**Issue by CastusVR** [sandstorm-io/sandcats#159]
Hello,

the certificate of the domain sandcats.io has expired today.
ERR_CERT_DATE_INVALID

In the sandstorm.log it says:
```
Couldn't send update sandcats hostname { Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'CERT_HAS_EXPIRED' }
```

**Comment by paulproteus** [comment]
I believe this is fixed now -- presumably due to work by @kentonv but I am not totally sure -- so I will mark this resolved. Cheers!

See: https://www.ssllabs.com/ssltest/analyze.html?d=sandcats.io&latest
